name: Continuous integration

on:
  push:
    branches:
    - "main"

jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: coursier/cache-action@v6.3
    - uses: VirtusLab/scala-cli-setup@v0.1
    - run: scala-cli test .